(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.golang.theory.
Require Export New.code.sys_verif_code.heap.linked_list.

Set Default Proof Using "Type".

Module linked_list.
Module Node.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : linked_list.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance Node_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (linked_list.Node.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "elem" ∷ l.[(linked_list.Node.t), "elem"] ↦{dq} v.(linked_list.Node.elem') ∗
      "next" ∷ l.[(linked_list.Node.t), "next"] ↦{dq} v.(linked_list.Node.next') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance Node_into_val_typed
   :
  IntoValTypedUnderlying (linked_list.Node.t) (linked_list.Nodeⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance Node_access_load_elem l (v : (linked_list.Node.t)) dq :
  AccessStrict
    (l.[(linked_list.Node.t), "elem"] ↦{dq} (v.(linked_list.Node.elem')))
    (l.[(linked_list.Node.t), "elem"] ↦{dq} (v.(linked_list.Node.elem')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Node_access_store_elem l (v : (linked_list.Node.t)) elem' :
  AccessStrict
    (l.[(linked_list.Node.t), "elem"] ↦ (v.(linked_list.Node.elem')))
    (l.[(linked_list.Node.t), "elem"] ↦ elem')
    (l ↦ v) (l ↦ (v <|(linked_list.Node.elem') := elem'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Node_access_load_next l (v : (linked_list.Node.t)) dq :
  AccessStrict
    (l.[(linked_list.Node.t), "next"] ↦{dq} (v.(linked_list.Node.next')))
    (l.[(linked_list.Node.t), "next"] ↦{dq} (v.(linked_list.Node.next')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Node_access_store_next l (v : (linked_list.Node.t)) next' :
  AccessStrict
    (l.[(linked_list.Node.t), "next"] ↦ (v.(linked_list.Node.next')))
    (l.[(linked_list.Node.t), "next"] ↦ next')
    (l ↦ v) (l ↦ (v <|(linked_list.Node.next') := next'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End Node.

End linked_list.
