(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.golang.theory.
Require Export New.code.sys_verif_code.algo.

Set Default Proof Using "Type".

Module algo.
Module Person.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : algo.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance Person_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (algo.Person.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "Name" ∷ l.[(algo.Person.t), "Name"] ↦{dq} v.(algo.Person.Name') ∗
      "Age" ∷ l.[(algo.Person.t), "Age"] ↦{dq} v.(algo.Person.Age') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance Person_into_val_typed
   :
  IntoValTypedUnderlying (algo.Person.t) (algo.Personⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance Person_access_load_Name l (v : (algo.Person.t)) dq :
  AccessStrict
    (l.[(algo.Person.t), "Name"] ↦{dq} (v.(algo.Person.Name')))
    (l.[(algo.Person.t), "Name"] ↦{dq} (v.(algo.Person.Name')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Person_access_store_Name l (v : (algo.Person.t)) Name' :
  AccessStrict
    (l.[(algo.Person.t), "Name"] ↦ (v.(algo.Person.Name')))
    (l.[(algo.Person.t), "Name"] ↦ Name')
    (l ↦ v) (l ↦ (v <|(algo.Person.Name') := Name'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Person_access_load_Age l (v : (algo.Person.t)) dq :
  AccessStrict
    (l.[(algo.Person.t), "Age"] ↦{dq} (v.(algo.Person.Age')))
    (l.[(algo.Person.t), "Age"] ↦{dq} (v.(algo.Person.Age')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Person_access_store_Age l (v : (algo.Person.t)) Age' :
  AccessStrict
    (l.[(algo.Person.t), "Age"] ↦ (v.(algo.Person.Age')))
    (l.[(algo.Person.t), "Age"] ↦ Age')
    (l ↦ v) (l ↦ (v <|(algo.Person.Age') := Age'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End Person.

End algo.
