(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.github_com.goose_lang.std.
Require Export New.generatedproof.sync.
Require Export New.generatedproof.sys_verif_code.concurrent.barrier.
Require Export New.golang.theory.
Require Export New.code.sys_verif_code.concurrent.

Set Default Proof Using "Type".

Module concurrent.
Module AtomicInt.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : concurrent.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance AtomicInt_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (concurrent.AtomicInt.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "x" ∷ l.[(concurrent.AtomicInt.t), "x"] ↦{dq} v.(concurrent.AtomicInt.x') ∗
      "mu" ∷ l.[(concurrent.AtomicInt.t), "mu"] ↦{dq} v.(concurrent.AtomicInt.mu') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance AtomicInt_into_val_typed
   :
  IntoValTypedUnderlying (concurrent.AtomicInt.t) (concurrent.AtomicIntⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance AtomicInt_access_load_x l (v : (concurrent.AtomicInt.t)) dq :
  AccessStrict
    (l.[(concurrent.AtomicInt.t), "x"] ↦{dq} (v.(concurrent.AtomicInt.x')))
    (l.[(concurrent.AtomicInt.t), "x"] ↦{dq} (v.(concurrent.AtomicInt.x')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance AtomicInt_access_store_x l (v : (concurrent.AtomicInt.t)) x' :
  AccessStrict
    (l.[(concurrent.AtomicInt.t), "x"] ↦ (v.(concurrent.AtomicInt.x')))
    (l.[(concurrent.AtomicInt.t), "x"] ↦ x')
    (l ↦ v) (l ↦ (v <|(concurrent.AtomicInt.x') := x'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance AtomicInt_access_load_mu l (v : (concurrent.AtomicInt.t)) dq :
  AccessStrict
    (l.[(concurrent.AtomicInt.t), "mu"] ↦{dq} (v.(concurrent.AtomicInt.mu')))
    (l.[(concurrent.AtomicInt.t), "mu"] ↦{dq} (v.(concurrent.AtomicInt.mu')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance AtomicInt_access_store_mu l (v : (concurrent.AtomicInt.t)) mu' :
  AccessStrict
    (l.[(concurrent.AtomicInt.t), "mu"] ↦ (v.(concurrent.AtomicInt.mu')))
    (l.[(concurrent.AtomicInt.t), "mu"] ↦ mu')
    (l ↦ v) (l ↦ (v <|(concurrent.AtomicInt.mu') := mu'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End AtomicInt.

End concurrent.
