(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.github_com.goose_lang.std.
Require Export New.golang.theory.
Require Export New.code.sys_verif_code.functional.

Set Default Proof Using "Type".

Module functional.
End functional.
