(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.github_com.goose_lang.std.
Require Export New.golang.theory.
Require Export New.code.sys_verif_code.heap.

Set Default Proof Using "Type".

Module heap.
Module S1.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : heap.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance S1_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (heap.S1.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "a" ∷ l.[(heap.S1.t), "a"] ↦{dq} v.(heap.S1.a') ∗
      "b" ∷ l.[(heap.S1.t), "b"] ↦{dq} v.(heap.S1.b') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance S1_into_val_typed
   :
  IntoValTypedUnderlying (heap.S1.t) (heap.S1ⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance S1_access_load_a l (v : (heap.S1.t)) dq :
  AccessStrict
    (l.[(heap.S1.t), "a"] ↦{dq} (v.(heap.S1.a')))
    (l.[(heap.S1.t), "a"] ↦{dq} (v.(heap.S1.a')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance S1_access_store_a l (v : (heap.S1.t)) a' :
  AccessStrict
    (l.[(heap.S1.t), "a"] ↦ (v.(heap.S1.a')))
    (l.[(heap.S1.t), "a"] ↦ a')
    (l ↦ v) (l ↦ (v <|(heap.S1.a') := a'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance S1_access_load_b l (v : (heap.S1.t)) dq :
  AccessStrict
    (l.[(heap.S1.t), "b"] ↦{dq} (v.(heap.S1.b')))
    (l.[(heap.S1.t), "b"] ↦{dq} (v.(heap.S1.b')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance S1_access_store_b l (v : (heap.S1.t)) b' :
  AccessStrict
    (l.[(heap.S1.t), "b"] ↦ (v.(heap.S1.b')))
    (l.[(heap.S1.t), "b"] ↦ b')
    (l ↦ v) (l ↦ (v <|(heap.S1.b') := b'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End S1.

Module Stack.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : heap.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance Stack_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (heap.Stack.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "elements" ∷ l.[(heap.Stack.t), "elements"] ↦{dq} v.(heap.Stack.elements') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance Stack_into_val_typed
   :
  IntoValTypedUnderlying (heap.Stack.t) (heap.Stackⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance Stack_access_load_elements l (v : (heap.Stack.t)) dq :
  AccessStrict
    (l.[(heap.Stack.t), "elements"] ↦{dq} (v.(heap.Stack.elements')))
    (l.[(heap.Stack.t), "elements"] ↦{dq} (v.(heap.Stack.elements')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Stack_access_store_elements l (v : (heap.Stack.t)) elements' :
  AccessStrict
    (l.[(heap.Stack.t), "elements"] ↦ (v.(heap.Stack.elements')))
    (l.[(heap.Stack.t), "elements"] ↦ elements')
    (l ↦ v) (l ↦ (v <|(heap.Stack.elements') := elements'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End Stack.

Module Queue.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : heap.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance Queue_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (heap.Queue.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "back" ∷ l.[(heap.Queue.t), "back"] ↦{dq} v.(heap.Queue.back') ∗
      "front" ∷ l.[(heap.Queue.t), "front"] ↦{dq} v.(heap.Queue.front') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance Queue_into_val_typed
   :
  IntoValTypedUnderlying (heap.Queue.t) (heap.Queueⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance Queue_access_load_back l (v : (heap.Queue.t)) dq :
  AccessStrict
    (l.[(heap.Queue.t), "back"] ↦{dq} (v.(heap.Queue.back')))
    (l.[(heap.Queue.t), "back"] ↦{dq} (v.(heap.Queue.back')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Queue_access_store_back l (v : (heap.Queue.t)) back' :
  AccessStrict
    (l.[(heap.Queue.t), "back"] ↦ (v.(heap.Queue.back')))
    (l.[(heap.Queue.t), "back"] ↦ back')
    (l ↦ v) (l ↦ (v <|(heap.Queue.back') := back'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Queue_access_load_front l (v : (heap.Queue.t)) dq :
  AccessStrict
    (l.[(heap.Queue.t), "front"] ↦{dq} (v.(heap.Queue.front')))
    (l.[(heap.Queue.t), "front"] ↦{dq} (v.(heap.Queue.front')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Queue_access_store_front l (v : (heap.Queue.t)) front' :
  AccessStrict
    (l.[(heap.Queue.t), "front"] ↦ (v.(heap.Queue.front')))
    (l.[(heap.Queue.t), "front"] ↦ front')
    (l ↦ v) (l ↦ (v <|(heap.Queue.front') := front'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End Queue.

Module SearchTree.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : heap.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance SearchTree_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (heap.SearchTree.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "key" ∷ l.[(heap.SearchTree.t), "key"] ↦{dq} v.(heap.SearchTree.key') ∗
      "left" ∷ l.[(heap.SearchTree.t), "left"] ↦{dq} v.(heap.SearchTree.left') ∗
      "right" ∷ l.[(heap.SearchTree.t), "right"] ↦{dq} v.(heap.SearchTree.right') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance SearchTree_into_val_typed
   :
  IntoValTypedUnderlying (heap.SearchTree.t) (heap.SearchTreeⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance SearchTree_access_load_key l (v : (heap.SearchTree.t)) dq :
  AccessStrict
    (l.[(heap.SearchTree.t), "key"] ↦{dq} (v.(heap.SearchTree.key')))
    (l.[(heap.SearchTree.t), "key"] ↦{dq} (v.(heap.SearchTree.key')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance SearchTree_access_store_key l (v : (heap.SearchTree.t)) key' :
  AccessStrict
    (l.[(heap.SearchTree.t), "key"] ↦ (v.(heap.SearchTree.key')))
    (l.[(heap.SearchTree.t), "key"] ↦ key')
    (l ↦ v) (l ↦ (v <|(heap.SearchTree.key') := key'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance SearchTree_access_load_left l (v : (heap.SearchTree.t)) dq :
  AccessStrict
    (l.[(heap.SearchTree.t), "left"] ↦{dq} (v.(heap.SearchTree.left')))
    (l.[(heap.SearchTree.t), "left"] ↦{dq} (v.(heap.SearchTree.left')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance SearchTree_access_store_left l (v : (heap.SearchTree.t)) left' :
  AccessStrict
    (l.[(heap.SearchTree.t), "left"] ↦ (v.(heap.SearchTree.left')))
    (l.[(heap.SearchTree.t), "left"] ↦ left')
    (l ↦ v) (l ↦ (v <|(heap.SearchTree.left') := left'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance SearchTree_access_load_right l (v : (heap.SearchTree.t)) dq :
  AccessStrict
    (l.[(heap.SearchTree.t), "right"] ↦{dq} (v.(heap.SearchTree.right')))
    (l.[(heap.SearchTree.t), "right"] ↦{dq} (v.(heap.SearchTree.right')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance SearchTree_access_store_right l (v : (heap.SearchTree.t)) right' :
  AccessStrict
    (l.[(heap.SearchTree.t), "right"] ↦ (v.(heap.SearchTree.right')))
    (l.[(heap.SearchTree.t), "right"] ↦ right')
    (l ↦ v) (l ↦ (v <|(heap.SearchTree.right') := right'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End SearchTree.

Module Person.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : heap.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance Person_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (heap.Person.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "FirstName" ∷ l.[(heap.Person.t), "FirstName"] ↦{dq} v.(heap.Person.FirstName') ∗
      "LastName" ∷ l.[(heap.Person.t), "LastName"] ↦{dq} v.(heap.Person.LastName') ∗
      "Age" ∷ l.[(heap.Person.t), "Age"] ↦{dq} v.(heap.Person.Age') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance Person_into_val_typed
   :
  IntoValTypedUnderlying (heap.Person.t) (heap.Personⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance Person_access_load_FirstName l (v : (heap.Person.t)) dq :
  AccessStrict
    (l.[(heap.Person.t), "FirstName"] ↦{dq} (v.(heap.Person.FirstName')))
    (l.[(heap.Person.t), "FirstName"] ↦{dq} (v.(heap.Person.FirstName')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Person_access_store_FirstName l (v : (heap.Person.t)) FirstName' :
  AccessStrict
    (l.[(heap.Person.t), "FirstName"] ↦ (v.(heap.Person.FirstName')))
    (l.[(heap.Person.t), "FirstName"] ↦ FirstName')
    (l ↦ v) (l ↦ (v <|(heap.Person.FirstName') := FirstName'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Person_access_load_LastName l (v : (heap.Person.t)) dq :
  AccessStrict
    (l.[(heap.Person.t), "LastName"] ↦{dq} (v.(heap.Person.LastName')))
    (l.[(heap.Person.t), "LastName"] ↦{dq} (v.(heap.Person.LastName')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Person_access_store_LastName l (v : (heap.Person.t)) LastName' :
  AccessStrict
    (l.[(heap.Person.t), "LastName"] ↦ (v.(heap.Person.LastName')))
    (l.[(heap.Person.t), "LastName"] ↦ LastName')
    (l ↦ v) (l ↦ (v <|(heap.Person.LastName') := LastName'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Person_access_load_Age l (v : (heap.Person.t)) dq :
  AccessStrict
    (l.[(heap.Person.t), "Age"] ↦{dq} (v.(heap.Person.Age')))
    (l.[(heap.Person.t), "Age"] ↦{dq} (v.(heap.Person.Age')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Person_access_store_Age l (v : (heap.Person.t)) Age' :
  AccessStrict
    (l.[(heap.Person.t), "Age"] ↦ (v.(heap.Person.Age')))
    (l.[(heap.Person.t), "Age"] ↦ Age')
    (l ↦ v) (l ↦ (v <|(heap.Person.Age') := Age'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End Person.

Module Rect.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : heap.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance Rect_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (heap.Rect.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "Width" ∷ l.[(heap.Rect.t), "Width"] ↦{dq} v.(heap.Rect.Width') ∗
      "Height" ∷ l.[(heap.Rect.t), "Height"] ↦{dq} v.(heap.Rect.Height') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance Rect_into_val_typed
   :
  IntoValTypedUnderlying (heap.Rect.t) (heap.Rectⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance Rect_access_load_Width l (v : (heap.Rect.t)) dq :
  AccessStrict
    (l.[(heap.Rect.t), "Width"] ↦{dq} (v.(heap.Rect.Width')))
    (l.[(heap.Rect.t), "Width"] ↦{dq} (v.(heap.Rect.Width')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Rect_access_store_Width l (v : (heap.Rect.t)) Width' :
  AccessStrict
    (l.[(heap.Rect.t), "Width"] ↦ (v.(heap.Rect.Width')))
    (l.[(heap.Rect.t), "Width"] ↦ Width')
    (l ↦ v) (l ↦ (v <|(heap.Rect.Width') := Width'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Rect_access_load_Height l (v : (heap.Rect.t)) dq :
  AccessStrict
    (l.[(heap.Rect.t), "Height"] ↦{dq} (v.(heap.Rect.Height')))
    (l.[(heap.Rect.t), "Height"] ↦{dq} (v.(heap.Rect.Height')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Rect_access_store_Height l (v : (heap.Rect.t)) Height' :
  AccessStrict
    (l.[(heap.Rect.t), "Height"] ↦ (v.(heap.Rect.Height')))
    (l.[(heap.Rect.t), "Height"] ↦ Height')
    (l ↦ v) (l ↦ (v <|(heap.Rect.Height') := Height'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End Rect.

End heap.
