(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.github_com.goose_lang.std.
Require Export New.golang.theory.
Require Export New.code.sys_verif_code.memoize.

Set Default Proof Using "Type".

Module memoize.
Module Memoize.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : memoize.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance Memoize_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (memoize.Memoize.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "f" ∷ l.[(memoize.Memoize.t), "f"] ↦{dq} v.(memoize.Memoize.f') ∗
      "results" ∷ l.[(memoize.Memoize.t), "results"] ↦{dq} v.(memoize.Memoize.results') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance Memoize_into_val_typed
   :
  IntoValTypedUnderlying (memoize.Memoize.t) (memoize.Memoizeⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance Memoize_access_load_f l (v : (memoize.Memoize.t)) dq :
  AccessStrict
    (l.[(memoize.Memoize.t), "f"] ↦{dq} (v.(memoize.Memoize.f')))
    (l.[(memoize.Memoize.t), "f"] ↦{dq} (v.(memoize.Memoize.f')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Memoize_access_store_f l (v : (memoize.Memoize.t)) f' :
  AccessStrict
    (l.[(memoize.Memoize.t), "f"] ↦ (v.(memoize.Memoize.f')))
    (l.[(memoize.Memoize.t), "f"] ↦ f')
    (l ↦ v) (l ↦ (v <|(memoize.Memoize.f') := f'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Memoize_access_load_results l (v : (memoize.Memoize.t)) dq :
  AccessStrict
    (l.[(memoize.Memoize.t), "results"] ↦{dq} (v.(memoize.Memoize.results')))
    (l.[(memoize.Memoize.t), "results"] ↦{dq} (v.(memoize.Memoize.results')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Memoize_access_store_results l (v : (memoize.Memoize.t)) results' :
  AccessStrict
    (l.[(memoize.Memoize.t), "results"] ↦ (v.(memoize.Memoize.results')))
    (l.[(memoize.Memoize.t), "results"] ↦ results')
    (l ↦ v) (l ↦ (v <|(memoize.Memoize.results') := results'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End Memoize.

Module MockMemoize.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : memoize.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance MockMemoize_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (memoize.MockMemoize.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "f" ∷ l.[(memoize.MockMemoize.t), "f"] ↦{dq} v.(memoize.MockMemoize.f') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance MockMemoize_into_val_typed
   :
  IntoValTypedUnderlying (memoize.MockMemoize.t) (memoize.MockMemoizeⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance MockMemoize_access_load_f l (v : (memoize.MockMemoize.t)) dq :
  AccessStrict
    (l.[(memoize.MockMemoize.t), "f"] ↦{dq} (v.(memoize.MockMemoize.f')))
    (l.[(memoize.MockMemoize.t), "f"] ↦{dq} (v.(memoize.MockMemoize.f')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance MockMemoize_access_store_f l (v : (memoize.MockMemoize.t)) f' :
  AccessStrict
    (l.[(memoize.MockMemoize.t), "f"] ↦ (v.(memoize.MockMemoize.f')))
    (l.[(memoize.MockMemoize.t), "f"] ↦ f')
    (l ↦ v) (l ↦ (v <|(memoize.MockMemoize.f') := f'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End MockMemoize.

End memoize.
