(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.generatedproof.github_com.goose_lang.std.
Require Export New.generatedproof.sync.
Require Export New.golang.theory.
Require Export New.code.sys_verif_code.concurrent.barrier.

Set Default Proof Using "Type".

Module barrier.
Module Barrier.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : barrier.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance Barrier_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (barrier.Barrier.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "numWaiting" ∷ l.[(barrier.Barrier.t), "numWaiting"] ↦{dq} v.(barrier.Barrier.numWaiting') ∗
      "mu" ∷ l.[(barrier.Barrier.t), "mu"] ↦{dq} v.(barrier.Barrier.mu') ∗
      "cond" ∷ l.[(barrier.Barrier.t), "cond"] ↦{dq} v.(barrier.Barrier.cond') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance Barrier_into_val_typed
   :
  IntoValTypedUnderlying (barrier.Barrier.t) (barrier.Barrierⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance Barrier_access_load_numWaiting l (v : (barrier.Barrier.t)) dq :
  AccessStrict
    (l.[(barrier.Barrier.t), "numWaiting"] ↦{dq} (v.(barrier.Barrier.numWaiting')))
    (l.[(barrier.Barrier.t), "numWaiting"] ↦{dq} (v.(barrier.Barrier.numWaiting')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Barrier_access_store_numWaiting l (v : (barrier.Barrier.t)) numWaiting' :
  AccessStrict
    (l.[(barrier.Barrier.t), "numWaiting"] ↦ (v.(barrier.Barrier.numWaiting')))
    (l.[(barrier.Barrier.t), "numWaiting"] ↦ numWaiting')
    (l ↦ v) (l ↦ (v <|(barrier.Barrier.numWaiting') := numWaiting'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Barrier_access_load_mu l (v : (barrier.Barrier.t)) dq :
  AccessStrict
    (l.[(barrier.Barrier.t), "mu"] ↦{dq} (v.(barrier.Barrier.mu')))
    (l.[(barrier.Barrier.t), "mu"] ↦{dq} (v.(barrier.Barrier.mu')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Barrier_access_store_mu l (v : (barrier.Barrier.t)) mu' :
  AccessStrict
    (l.[(barrier.Barrier.t), "mu"] ↦ (v.(barrier.Barrier.mu')))
    (l.[(barrier.Barrier.t), "mu"] ↦ mu')
    (l ↦ v) (l ↦ (v <|(barrier.Barrier.mu') := mu'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Barrier_access_load_cond l (v : (barrier.Barrier.t)) dq :
  AccessStrict
    (l.[(barrier.Barrier.t), "cond"] ↦{dq} (v.(barrier.Barrier.cond')))
    (l.[(barrier.Barrier.t), "cond"] ↦{dq} (v.(barrier.Barrier.cond')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Barrier_access_store_cond l (v : (barrier.Barrier.t)) cond' :
  AccessStrict
    (l.[(barrier.Barrier.t), "cond"] ↦ (v.(barrier.Barrier.cond')))
    (l.[(barrier.Barrier.t), "cond"] ↦ cond')
    (l ↦ v) (l ↦ (v <|(barrier.Barrier.cond') := cond'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End Barrier.

End barrier.
